-- PostgreSQL schema parity for the MVP3 isolated simulation overlay runtime.
CREATE TABLE IF NOT EXISTS simulation_reference_configs (tenant_id TEXT NOT NULL, key TEXT NOT NULL CHECK(char_length(key) BETWEEN 1 AND 64), value_json JSONB NOT NULL, resource_version BIGINT NOT NULL CHECK(resource_version > 0), updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(tenant_id,key));
CREATE TABLE IF NOT EXISTS simulation_reference_resource_revisions (tenant_id TEXT NOT NULL, key TEXT NOT NULL, resource_version BIGINT NOT NULL CHECK(resource_version > 0), present BOOLEAN NOT NULL, updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(tenant_id,key));
CREATE TABLE IF NOT EXISTS simulation_tenant_revisions (tenant_id TEXT PRIMARY KEY, revision BIGINT NOT NULL CHECK(revision >= 0), updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS simulation_sessions (id TEXT NOT NULL, actor_id TEXT NOT NULL, target_tenant_id TEXT NOT NULL, namespace_id TEXT NOT NULL UNIQUE, base_revision BIGINT NOT NULL, generation BIGINT NOT NULL DEFAULT 1 CHECK(generation >= 1), idempotency_key_hash TEXT NOT NULL, create_request_digest TEXT NOT NULL, scenario_name TEXT NOT NULL CHECK(char_length(scenario_name) BETWEEN 1 AND 80), change_intent TEXT NOT NULL CHECK(char_length(change_intent) BETWEEN 1 AND 500), status TEXT NOT NULL CHECK(status IN ('provisioning','active','expired','discarded','failed')), created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, provisioning_lease_until TIMESTAMPTZ, discarded_at TIMESTAMPTZ, failure_code TEXT, PRIMARY KEY(id,target_tenant_id), UNIQUE(actor_id,idempotency_key_hash), CHECK(expires_at > created_at));
CREATE INDEX IF NOT EXISTS idx_simulation_sessions_actor_status ON simulation_sessions(actor_id,status,expires_at);
CREATE INDEX IF NOT EXISTS idx_simulation_sessions_tenant ON simulation_sessions(target_tenant_id,created_at DESC);
CREATE TABLE IF NOT EXISTS simulation_revision_evidence (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, resource_kind TEXT NOT NULL, resource_key TEXT NOT NULL, base_presence BOOLEAN NOT NULL, captured_resource_version BIGINT NOT NULL, PRIMARY KEY(simulation_id,tenant_id,resource_kind,resource_key), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_base_documents (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, resource_kind TEXT NOT NULL, resource_key TEXT NOT NULL, base_resource_version BIGINT NOT NULL, document_json JSONB NOT NULL, payload_policy TEXT NOT NULL DEFAULT 'REFERENCE_ONLY', captured_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(simulation_id,tenant_id,resource_kind,resource_key), FOREIGN KEY(simulation_id,tenant_id,resource_kind,resource_key) REFERENCES simulation_revision_evidence(simulation_id,tenant_id,resource_kind,resource_key) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_overlay_entries (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, resource_kind TEXT NOT NULL, resource_key TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('value','tombstone')), document_json JSONB, base_resource_version BIGINT NOT NULL, overlay_version BIGINT NOT NULL CHECK(overlay_version > 0), created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(simulation_id,tenant_id,resource_kind,resource_key), FOREIGN KEY(simulation_id,tenant_id,resource_kind,resource_key) REFERENCES simulation_revision_evidence(simulation_id,tenant_id,resource_kind,resource_key) ON DELETE RESTRICT, CHECK((operation = 'value' AND document_json IS NOT NULL) OR (operation = 'tombstone' AND document_json IS NULL)));
CREATE TABLE IF NOT EXISTS simulation_usage (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, overlay_rows BIGINT NOT NULL DEFAULT 0, document_bytes BIGINT NOT NULL DEFAULT 0, effect_count BIGINT NOT NULL DEFAULT 0, evaluation_count BIGINT NOT NULL DEFAULT 0, evidence_bytes BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(simulation_id,tenant_id), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_command_results (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, actor_id TEXT NOT NULL, command TEXT NOT NULL, command_idempotency_key_hash TEXT NOT NULL, request_digest TEXT NOT NULL, response_status INTEGER NOT NULL, response_json JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(simulation_id,actor_id,command,command_idempotency_key_hash), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_effect_records (id TEXT PRIMARY KEY, simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, actor_id TEXT NOT NULL, command TEXT NOT NULL, command_idempotency_key_hash TEXT NOT NULL, request_digest TEXT NOT NULL, effect_ordinal INTEGER NOT NULL, effect_kind TEXT NOT NULL, payload_policy TEXT NOT NULL, payload_preview TEXT NOT NULL, deterministic_result JSONB NOT NULL, correlation_id TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, UNIQUE(simulation_id,actor_id,command,command_idempotency_key_hash,effect_ordinal), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_diff_evidence (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, evaluation_id TEXT NOT NULL, evaluated_revision BIGINT NOT NULL, generation BIGINT NOT NULL, overlay_digest TEXT NOT NULL, item_count BIGINT NOT NULL, total_bytes BIGINT NOT NULL, digest TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('ready','pending','failed')), created_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(simulation_id,tenant_id,evaluation_id), UNIQUE(simulation_id,generation,evaluated_revision,overlay_digest), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_diff_evidence_items (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, evaluation_id TEXT NOT NULL, ordinal INTEGER NOT NULL, canonical_item_json JSONB NOT NULL, item_bytes INTEGER NOT NULL, PRIMARY KEY(simulation_id,tenant_id,evaluation_id,ordinal), FOREIGN KEY(simulation_id,tenant_id,evaluation_id) REFERENCES simulation_diff_evidence(simulation_id,tenant_id,evaluation_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_terminal_inputs (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, generation BIGINT NOT NULL, evaluated_revision BIGINT NOT NULL, overlay_digest TEXT NOT NULL, item_count BIGINT NOT NULL, input_bytes BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(simulation_id,tenant_id,generation), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_terminal_input_items (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, generation BIGINT NOT NULL, ordinal INTEGER NOT NULL, canonical_input_json JSONB NOT NULL, item_bytes INTEGER NOT NULL, PRIMARY KEY(simulation_id,tenant_id,generation,ordinal), FOREIGN KEY(simulation_id,tenant_id,generation) REFERENCES simulation_terminal_inputs(simulation_id,tenant_id,generation) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_cleanup_jobs (simulation_id TEXT NOT NULL, tenant_id TEXT NOT NULL, job_kind TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('pending','running','complete','failed')), attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at TIMESTAMPTZ NOT NULL, last_error_code TEXT, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(simulation_id,tenant_id,job_kind), FOREIGN KEY(simulation_id,tenant_id) REFERENCES simulation_sessions(id,target_tenant_id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS simulation_rate_buckets (actor_id TEXT NOT NULL, simulation_id TEXT NOT NULL, operation_class TEXT NOT NULL, window_start TIMESTAMPTZ NOT NULL, request_count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(actor_id,simulation_id,operation_class,window_start));
