#!/usr/bin/env node
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import process from 'node:process';import {spawnSync} from 'node:child_process'
const root=process.cwd(),checker=path.join(root,'scripts/check-r3-damage-settlement-clock-boundary.mjs'),files=['backend/src/db/migrations/063_r3_damage_settlement_clock.sql','backend/src/db/migrations/postgres/063_r3_damage_settlement_clock.sql','backend/src/db/migrations/064_r3_settlement_integration_authority.sql','backend/src/db/migrations/postgres/064_r3_settlement_integration_authority.sql','backend/src/db/migrations/065_r3_terminal_settlement_seal.sql','backend/src/db/migrations/postgres/065_r3_terminal_settlement_seal.sql','backend/src/db/migrations.rs','backend/src/db/migrations_pg.rs','backend/src/integration/settlement_admission.rs','backend/src/repositories/r3_settlement.rs','backend/src/repositories/lifecycle.rs','backend/src/repositories/contracts/provider.rs','backend/src/repositories/mod.rs','backend/src/application/r3_settlement.rs','backend/src/application/rental_time.rs','backend/src/application/r3_settlement_tests.rs','backend/src/routes/r3_settlement.rs','backend/src/routes/mod.rs','backend/src/registry/descriptors.rs','backend/src/registry/factory.rs','policy/qualification/legacy-evidence/docs/proposals/talos-ops-business-closure/r3-sp-24-damage-repair-settlement.md','policy/qualification/legacy-evidence/docs/proposals/talos-ops-business-closure/r3-sp-25-clock-calendar-migration.md','policy/qualification/legacy-evidence/docs/proposals/talos-ops-business-closure/r3-sp-26-observability.md','policy/qualification/legacy-evidence/docs/proposals/talos-ops-business-closure/r3-sp-27-debug-sync-retirement.md','package.json']
function run(fixtureRoot=root){return spawnSync(process.execPath,[checker],{cwd:root,env:{...process.env,TALOS_R3_ROOT:fixtureRoot},encoding:'utf8'})}function fixture(){const temp=fs.mkdtempSync(path.join(os.tmpdir(),'talos-r3-'));for(const rel of files){const to=path.join(temp,rel);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(path.join(root,rel),to)}return temp}function expectFailure(name,rel,search,replacement,evidence){const temp=fixture();try{const file=path.join(temp,rel);fs.writeFileSync(file,fs.readFileSync(file,'utf8').replaceAll(search,replacement));const result=run(temp);if(result.status===0||!`${result.stdout}${result.stderr}`.includes(evidence))throw new Error(`${name} did not fail closed\n${result.stdout}\n${result.stderr}`)}finally{fs.rmSync(temp,{recursive:true,force:true})}}
const baseline=run();if(baseline.status!==0)throw new Error(`baseline TALOS-OPS-R3 failed\n${baseline.stdout}\n${baseline.stderr}`)
expectFailure('R2 effect admission authority','backend/src/integration/settlement_admission.rs','EffectIntent','OtherIntent','EffectIntent')
expectFailure('R3 has no duplicate outcome authority','backend/src/repositories/r3_settlement.rs','admit_settlement_charge_tx','other_admission','admit_settlement_charge_tx')
expectFailure('atomic terminal close','backend/src/repositories/r3_settlement.rs','close_order_atomic','close_order_separately','close_order_atomic')
expectFailure('financial reservation','backend/src/repositories/r3_settlement.rs','assert_financial_reservation','other_reservation','assert_financial_reservation')
expectFailure('multi-admission exact aggregation','backend/src/repositories/r3_settlement.rs','load_financial_effect_summary','other_financial_summary','load_financial_effect_summary')
expectFailure('terminal settlement seal','backend/src/db/migrations/065_r3_terminal_settlement_seal.sql','r3_terminal_settlement_case_seal','other_terminal_settlement_case_seal','r3_terminal_settlement_case_seal')
expectFailure('SQLite terminal settlement OLD-authority seal','backend/src/db/migrations/065_r3_terminal_settlement_seal.sql','OLD.tenant_id','NEW.tenant_id','OLD.tenant_id')
expectFailure('PostgreSQL terminal settlement OLD-authority seal','backend/src/db/migrations/postgres/065_r3_terminal_settlement_seal.sql',"TG_OP='UPDATE'","TG_OP='INSERT'","TG_OP='UPDATE'")
expectFailure('canonical device state','backend/src/repositories/r3_settlement.rs','txt::STATUS_CHECKED_IN','available','txt::STATUS_CHECKED_IN')
expectFailure('admin liability','backend/src/application/r3_settlement.rs','admin_write("decide_liability")','write("decide_liability")','decide_liability')
expectFailure('Registry-only route','backend/src/routes/r3_settlement.rs','"r3_settlement"','"other_module"','backend/src/routes/r3_settlement.rs: missing')
expectFailure('explicit timestamp parser','backend/src/application/rental_time.rs','parse_from_rfc3339','parse_from_local','parse_from_rfc3339')
expectFailure('deferred SP-22 statement','policy/qualification/legacy-evidence/docs/proposals/talos-ops-business-closure/r3-sp-24-damage-repair-settlement.md','SP-22','SP-XX','SP-22')
const crlf=fixture();try{for(const rel of files){const file=path.join(crlf,rel);fs.writeFileSync(file,fs.readFileSync(file,'utf8').replaceAll('\r\n','\n').replaceAll('\n','\r\n'))}const result=run(crlf);if(result.status!==0)throw new Error(`CRLF parity failed\n${result.stdout}\n${result.stderr}`)}finally{fs.rmSync(crlf,{recursive:true,force:true})}
process.stdout.write('TALOS-OPS-R3 negative fixtures and CRLF parity passed.\n')
